---
abstract: 'Deploy your code to the Phenona platform'
author:
  - 'Daniil Kulchenko <daniil@kulchenko.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200004, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Phenona
requires:
  Carp: 0
  File::Path: 0
  IO::Prompt: 0
  LWP::Simple: 0
  LWP::UserAgent: 0
  Net::SFTP::Foreign: 0
  YAML::Any: 0
version: 0.003
